### ISSUE TITLE
enable clang-tidy by opt-in

### ISSUE THREAD

**Issue by metaflow** [google/llvm-premerge-checks#367]

**Comment by ChristianKuehnel** [comment]
I would be great to have such a feature for `/clang-tools-extra/clangd`. We recently cleaned up a couple of findings in our subfolder and we would like to prevent backsliding.

**Comment by joker-eph** [comment]
Please bring back clang-tidy, that was really valuable to have on review when it was enabled!

I just landed > 27 commits to fix various clang-tidy issues in `mlir/`.

**Comment by ChristianKuehnel** [comment]
@metaflow I would be interesting in working on this as we would like to use it for clangd.

I guess this would involve:
* Investigate how much of clang-tidy-diff.py and run-clang-tidy.py we could reuse and replace our own logic. 
* Unify all the clang-tidy related config options into a single yaml file to make configuration easier.
* Introduce a new config option to suppress findings using a mix of include and exclude rules using path prefixes (as today).  I'm thinking of something like this to only enable for MLIR:
 ```yaml
# The first matching rule is applied in the order of their definition. 

# excludes from the current clang-tidy.ignore
- exclude:
  - mlir/examples/standalone
  - mlir/include/mlir-c/Bindings
  - mlir/include/mlir/Bindings
  - mlir/lib/Bindings
  - mlir/test
  - mlir/tools/mlir-cuda-runner
  - mlir/tools/mlir-rocm-runner
# turn on for the rest of mlir
- include: 
   - /mlir
# turn off for all other paths
- exclude:
  - /
 ```
* As this would be a significant refactoring, migrate the new/changes scripting to the monorepo. 
  * This would be a step towards #186 .
  * However then the pre-merge scripting would be distributed across 2 repos (until we migrate the rest some day).
  * We would need to figure out where to put these files in the monorepo.
* integration of this script with the pipeline:
  * Input: git hash to analyze (or last git commit if no hash was set)
  * Output: filtered clang-tidy findings as Python object or JSON
  * The caller of this script would then need to take the findings and upload them to Phabricator
  * The new script would be run on Linux after the build, so that all necessary header were generated already.
